# Compiles the Vulkan fixture GLSL shaders into an embedded SPIR-V header.
#
# Usage:
#   pwsh -NoProfile -File scripts/compile_vk_shaders.ps1 [-Glslang <path>]
#
# Requires a glslang build (the Vulkan SDK provides glslangValidator; standalone
# glslang releases provide glslang.exe). The default path is the developer tool
# downloaded into src_rebuild/dependencies/vulkan-tools/glslang.exe.
#
# Output: src_rebuild/PsyCross/src/render/PsyX_Vk_Shaders.h

param(
	[string]$Glslang = ''
)

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
if (-not $Glslang) {
	$Glslang = Join-Path $repoRoot 'src_rebuild/dependencies/vulkan-tools/glslang.exe'
}

if (-not (Test-Path -LiteralPath $Glslang)) {
	throw "glslang not found at '$Glslang'. Pass -Glslang <path>."
}

$shaderDir = Join-Path $repoRoot 'src_rebuild/PsyCross/src/render/vk_shaders'
$output = Join-Path $repoRoot 'src_rebuild/PsyCross/src/render/PsyX_Vk_Shaders.h'

$shaders = @(
	@{ Name = 'fixture_vert'; File = 'fixture.vert' },
	@{ Name = 'fixture_frag'; File = 'fixture.frag' },
	@{ Name = 'shadow_vert';  File = 'shadow.vert'  },
	@{ Name = 'shadow_frag';  File = 'shadow.frag'  },
	@{ Name = 'fullscreen_vert';    File = 'fullscreen.vert'    },
	@{ Name = 'psx_modern_vert';    File = 'psx_modern.vert'    },
	@{ Name = 'psx_modern_frag';    File = 'psx_modern.frag'    },
	@{ Name = 'psx_composite_frag'; File = 'psx_composite.frag' },
	@{ Name = 'psx_vert';     File = 'psx.vert'     },
	# vulkan1.1 keeps `discard` as OpKill instead of OpDemoteToHelperInvocation,
	# so the PSX shader runs on any Vulkan 1.1 device without enabling the
	# shaderDemoteToHelperInvocation feature. The shader has no derivatives, so
	# the two have the same effect here.
	@{ Name = 'psx_frag';     File = 'psx.frag'; Target = 'vulkan1.1' }
)

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('/* Generated by scripts/compile_vk_shaders.ps1 from vk_shaders/*.glsl.')
$lines.Add('   Do not edit; rerun the script after changing a shader. */')
$lines.Add('')
$lines.Add('#ifndef PSYX_VK_SHADERS_H')
$lines.Add('#define PSYX_VK_SHADERS_H')
$lines.Add('')

foreach ($shader in $shaders) {
	$source = Join-Path $shaderDir $shader.File
	$spirv = Join-Path $shaderDir ($shader.File + '.spv')

	$target = if ($shader.Target) { $shader.Target } else { 'vulkan1.3' }
	& $Glslang -V $source -o $spirv --target-env $target | Out-Null
	if ($LASTEXITCODE -ne 0) {
		throw "glslang failed for $($shader.File)"
	}

	$bytes = [System.IO.File]::ReadAllBytes($spirv)
	if (($bytes.Length % 4) -ne 0) {
		throw "$($shader.File).spv is not a whole number of 32-bit words"
	}

	$wordCount = $bytes.Length / 4
	$lines.Add("static const unsigned int $($shader.Name)_spv[$wordCount] = {")

	$chunk = [System.Collections.Generic.List[string]]::new()
	for ($i = 0; $i -lt $wordCount; $i++) {
		$word = [BitConverter]::ToUInt32($bytes, $i * 4)
		$chunk.Add(('0x{0:X8}' -f $word))
		if ($chunk.Count -eq 8 -or $i -eq ($wordCount - 1)) {
			$lines.Add("`t" + ($chunk -join ', ') + ',')
			$chunk.Clear()
		}
	}

	$lines.Add('};')
	$lines.Add("static const unsigned int $($shader.Name)_spv_size = $wordCount;")
	$lines.Add('')
}

$lines.Add('#endif // PSYX_VK_SHADERS_H')
$lines.Add('')

Set-Content -LiteralPath $output -Value $lines -Encoding UTF8
Write-Host "Wrote $output"
